name: Reuse other workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: ./.github/workflows/reuseable.yml
    with:
      who-to-greet: '@matuck'
  use-output:
    needs: call-workflow
    runs-on: ubuntu-latest
    steps:
      - run: echo "Time ran wqas ${{ needs.call-workflow.outputs.current-time }}
